name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/vaughnw128/eternalpose
          tags: |
            type=sha

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            git_sha=${{ github.sha }}          

  release:
    name: "Release to Immanent Grove"
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Open Immanent Grove PR
        env:
          ENV_REPO: ${{ github.event.repository.owner.name }}/immanent-grove
        uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: application-update.yml
          repo: ${{ env.ENV_REPO }}
          token: ${{ secrets.RELEASE_TOKEN }}
          inputs: '{"tag_name": "${{ needs.build.outputs.tag }}", "app_repo": "${{ github.event.repository.name }}", "image": "${{ github.event.repository.full_name }}:${{ needs.build.outputs.tag }}"}'
          ref: refs/heads/main